### ISSUE TITLE
[Feature Required]

### ISSUE THREAD

**Issue by juba0x00** [Mostafa-ewida/DSP-project#1]
@Mostafa-ewida 
I'm so lazy, can you clone the repository and run it for me :angry:

**Comment by Mostafa-ewida** [comment]
go run it yourself you lazy a$$ @juba0x00 

![image](https://github.com/Mostafa-ewida/DSP-project/assets/71707534/1ca9c707-d8bb-4942-a900-72e7335fa6f8)

**Comment by juba0x00** [comment]
@Mostafa-ewida 
![image](https://github.com/Mostafa-ewida/DSP-project/assets/73611543/a4b5c14f-270e-4b19-89ee-29aa3b2e93a2)

**Comment by Mostafa-ewida** [comment]
> @Mostafa-ewida ![image](https://private-user-images.githubusercontent.com/73611543/330582991-a4b5c14f-270e-4b19-89ee-29aa3b2e93a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MTk0MTMsIm5iZiI6MTcxNTcxOTExMywicGF0aCI6Ii83MzYxMTU0My8zMzA1ODI5OTEtYTRiNWMxNGYtMjcwZS00YjE5LTg5ZWUtMjlhYTNiMmU5M2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDIwMzgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ZDU3ODk0ZmZmZDhhMDRhZWIzNTg5YjY1MmU5MWJjYmNkYzFiYTI1MzE0NjUxMjkzMTg5ODJmMWNhYzIxOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nMVCeb0tb231I_zSXoOeZqo8CIRgdUv00NpDTnQJTrc)


![image](https://github.com/Mostafa-ewida/DSP-project/assets/71707534/7a6c8403-1eb3-4b96-9764-e69929fe0381)
